---------------
Authors: Team GPS

    TANAKA   Tetsurou   田中 哲朗   <ktanaka at ecc dot u-tokyo dot ac dot jp>
    KANEKO   Tomoyuki   金子 知適   <kaneko at graco dot c dot u-tokyo dot ac dot jp>
    MORIWAKI Daigo      森脇 大悟   <daigo at debian dot org>
    SOEDA    Shunsuke   副田 俊介   <me at shnsk dot net>
    HAYASHI  Yoshiki    林   芳樹   <yoshiki at xemacs dot org>
    TAKEUCHI Shougo     竹内 聖悟   <takeuchi at erato dot ist dot hokudai dot ac dot jp>

---------------
